### ISSUE TITLE
Bug: Persephone v0.17.3-alpha displays black squares instead of covers in macOS 11.0.1

### ISSUE THREAD

**Issue by odkr** [danbee/persephone#78] opened 2020-11-26 17:50 UTC
The title says it all really. Persephone does display the covers correctly in the queue though. Light/dark mode make no difference. I'm using Music Player Daemon v0.21.5.

<img width="1259" alt="Screenshot 2020-11-26 at 18 34 07" src="https://user-images.githubusercontent.com/21236809/100380044-577aa000-3016-11eb-949c-ee3b0ed71eb3.png">

**Comment by danbee** [comment] 2021-01-28 19:23
@odkr Thanks for this report. I've only just upgraded to Big Sur myself and I'm seeing the same issue.

**Comment by danbee** [comment] 2021-01-28 21:02
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/165531/106198541-2cc9d680-6182-11eb-8b25-792bd9f0bc72.png">

I've fixed the build on Big Sur, but as you can see there are other issues that need to be resolved now too.

**Comment by odkr** [comment] 2021-02-03 08:59
That’s great! I’m looking forward to being able to browse my music again :-).

**Comment by catap** [comment] 2021-02-05 14:51
Just for tracking: Version 0.17.3-alpha (411) on BigSur still has this issue

Screenshot:
![Screenshot 2021-02-05 at 15 50 07](https://user-images.githubusercontent.com/37775/107049150-0b906800-67ca-11eb-982d-44df77767fd7.png)

**Comment by danbee** [comment] 2021-02-05 15:00
Hi @catap, are you referring to the black album covers in the album list or something else? Other than that I can't see anything else wrong with the screenshot you posted.

**Comment by catap** [comment] 2021-02-05 15:02
@danbee I refer tp black square instead of album art.

I also try to build the last master 84a452931eda91bc114d9620628ac443d93b2a94 and it looks the same.

I'm using macOS 11.1 (20C69)

**Comment by danbee** [comment] 2021-02-05 15:15
@catap I will update this thread when the issue is fixed.

**Comment by danbee** [comment] 2021-02-15 13:52
Resolved by release [0.18.0-alpha](https://github.com/danbee/persephone/releases/tag/0.18.0-alpha)

**Closed by danbee** 2021-02-15 13:52 UTC
